Add licensing info, bump version to 3.12.1, fix exits

diff --git a/ocaml.SlackBuild b/ocaml.SlackBuild
--- a/ocaml.SlackBuild
+++ b/ocaml.SlackBuild
@@ -1,14 +1,31 @@
 #!/bin/sh
 #
-# SlackBuild for OCaml
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for Ocaml
+# Copyright (C) 2009-2011 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
 # Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
+# $Id: ocaml.SlackBuild,v 1.3 2011/12/18 14:21:26 gsotirov Exp $
+#
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=ocaml
-VERSION=3.12.0
+VERSION=3.12.1
 BUILD=${BUILD:-1}
 
 TMP=${TMP:-/tmp}
@@ -33,28 +50,28 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -xvf $CWD/$NAME-$VERSION.tar.bz2
+tar -xvf $CWD/$NAME-$VERSION.tar.bz2 || exit 3
 cd $SRC
 fix_source
 
 # Configure
 ./configure --host $ARCH-slackware-linux \
             --prefix /usr \
-            --libdir /usr/lib/$NAME \
-            --mandir /usr/man || exit 1
+            --libdir /usr/lib${LIBDIRSUFFIX}/$NAME \
+            --mandir /usr/man || exit 4
 
 sed -i -e "s/\\(BYTECCCOMPOPTS=.*\\)/\\1 ${SLKCFLAGS}/"   config/Makefile
 sed -i -e "s/\\(NATIVECCCOMPOPTS=.*\\)/\\1 ${SLKCFLAGS}/" config/Makefile
 
 # Build
-make world.opt || exit 2
+make world.opt || exit 5
 
 # Install
 make PREFIX=$PKG \
      BINDIR=$PKG/usr/bin \
-     LIBDIR=$PKG/usr/lib/$NAME \
+     LIBDIR=$PKG/usr/lib${LIBDIRSUFFIX}/$NAME \
      MANDIR=$PKG/usr/man \
-     install || exit 3
+     install || exit 6
 
 # Prepare
 bin_perms $PKG
@@ -72,6 +89,7 @@ install -m 644 $CWD/slack-desc       $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-required
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -79,6 +97,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Cleanup
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
